### PR TITLE
Eng 7185 danone aem connector aem cloud sdk compatability

### PR DESCRIPTION
**Pull request by Matvey-Davidson**
https://lilt.atlassian.net/browse/ENG-7185

This PR contains changes needed to support the AEM Cloud version of the connector, it is not going to be merged to aem650 but will be another branch. 

I aligned my adoption with the main branch of [AEM example](https://github.com/Adobe-Marketing-Cloud/aem-translation-framework-bootstrap-connector) that suppose to support AEM Cloud and this documentation https://experienceleague.adobe.com/docs/experience-manager-65/deploying/restructuring/repository-restructuring.html?lang=en

It was tested on the local environment ( and can be taken from here [Adobe Software Distribution](https://experience.adobe.com/#/downloads/content/software-distribution/en/aemcloud.html?package=/content/software-distribution/en/details.html/content/dam/aemcloud/public/aem-sdk-2023.6.12255.20230608T053118Z-230400.zip), credentials on Keeper) and  [cloud environment](https://experience.adobe.com/#/@lilttechnologypartner/cloud-manager/home.html/program/116153)

**Limitation**
The limitation that it currently has is that the translation statuses that are controlled by the connector are not always showing correctly [Translation Statuses](https://acrobat.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A32824bd9-6cc6-41b4-bc7b-8e7c4d2c7d65&viewer%21megaVerb=group-discover), it can jump from `COMMITED_FOR _TRANSLATION` to `READY_FOR _REVIEW`, I am still working on it

### CODE REVIEW

**Review by tgallant — APPROVED** [review]
the changes LGTM!

> it is not going to be merged to aem650 but will be another branch.

which branch do you want to merge it into? maybe we should make the branch first and update the PR so we can merge this into that branch.

**Comment by Matvey-Davidson** [comment]
> the changes LGTM!
> 
> > it is not going to be merged to aem650 but will be another branch.
> 
> which branch do you want to merge it into? maybe we should make the branch first and update the PR so we can merge this into that branch.

**Comment by Matvey-Davidson** [comment]
> > the changes LGTM!
> > > it is not going to be merged to aem650 but will be another branch.
> > 
> > 
> > which branch do you want to merge it into? maybe we should make the branch first and update the PR so we can merge this into that branch.

I was thinking about a branch called `aem_cloud`, I could just change the name of the current branch. What do you think?

**Comment by tgallant** [comment]
@Matvey-Davidson sure, let's make a new branch called `aem_cloud` that is branched from the `aem650` branch. then we can update the PR to merge into `aem_cloud` and the diff should look the same

**Comment by Matvey-Davidson** [comment]
> @Matvey-Davidson sure, let's make a new branch called `aem_cloud` that is branched from the `aem650` branch. then we can update the PR to merge into `aem_cloud` and the diff should look the same
Done!

**Pull request merged**
